### PR TITLE
Import guide for Cobalt + minor corrections to optimization.md

### PR DESCRIPTION
**Pull request by UberGruber**
minor typos, spelling, grammar fixes

### CODE REVIEW

**Comment by UberGruber** [comment]
I made a simple guide for the Import feature of Cobalt, use it if you think it's valuable! Beware tho that the images linked are from Cobalt forum posts and 1 from imgur, guess its better to store them somewhere more appropriate!

**Comment by pepperstreet** [comment]
Nice, but I think you should contribute to the **documentation** area:
http://docs.mintjoomla.com
How To:
http://youtu.be/KZyoYjCyt0s

Thanks in advance!

**Comment by UberGruber** [comment]
mmm isn't this the right repo? I'm not a git pro, have I messed up with something? I can see that the merge is ready but ofc It must be accepted by someone with write access

**Comment by pepperstreet** [comment]
@UberGruber Sure it is! My fault, I am no git-pro either!!! ;)

**Pull request merged**
